### PR TITLE
Docs for the Interactive graphics component

### PR DESCRIPTION
**Pull request by hcarneiro**
# Interactive Graphics JS APIs

These public JS APIs will be automatically available in your screens once a **Interactive graphics** component is dropped into such screens.

## Hooks
The Interactive graphics component exposes a few hooks that you can use to modify the data and behaviour of the component, here are the hooks and their specific life cycle:

**Before getting data source data**  
`flInteractiveGraphicsBeforeGetData`

**Before rendering the maps and markers**  
`flInteractiveGraphicsBeforeRender`

**After everything is rendered and the user clicks on the marker label**  
`flInteractiveGraphicsLabelClick`

### flInteractiveGraphicsBeforeGetData
Data available:

- **data** - Object containing properties listed below
  - **id** - (Number) The component's ID
  - **uuid** - (String) The component's UUID
  - **config** - (Object) The component's configuration settings
  - **container** - (DOM) The component's DOM selector

#### Setting new data
As a developer you can use this hook to get the data manually and modify the data before passing it to the component. You can do that by defining the following.
- **data.config.getData** - (Promise) Required to return an `Array` on entries

### flInteractiveGraphicsBeforeRender
Data available:

- **data** - Object containing properties listed below
  - **id** - (Number) The component's ID
  - **uuid** - (String) The component's UUID
  - **config** - (Object) The component's configuration settings
  - **container** - (DOM) The component's DOM selector
  - **markers** - (Array) The list of markers and their data

As a developer you can use this hook to load the map with a specific marker selected (this will also automatically select the correct map for the selected marker), or load a specific marker. You can do that by returning the following:

- `{ markerId: 1234 }` - Select a marker by ID
- `{ markerId: 1234 }` - Select a marker by Name
- `{ mapName: 'Map one' }` - Select a map

### flInteractiveGraphicsLabelClick
Data available:

- **data** - Object containing properties listed below
  - **id** - (Number) The component's ID
  - **uuid** - (String) The component's UUID
  - **config** - (Object) The component's configuration settings
  - **container** - (DOM) The component's DOM selector
  - **selectedMarker** - (Object) The selected marker data

Nothing is expected to be returned, the developer can write what should happen when the label is clicked

### Run a hook before getting the markers data

```js
Fliplet.Hooks.on('flInteractiveGraphicsBeforeGetData', function onBeforeGetData(data) {
  // disable caching the data so it's always retrieved from the server
  data.config.cache = false;

  // Define the "getData" promise to manually fetching data
  data.config.getData = function () {
    // In this example we connect to a datasource with ID 123
    // Change the ID to your data source ID
    return Fliplet.DataSources.connect(123)
      .then(function(connection) {
      // Get all entries in the data source matching a specific condition
      return connection.find({
        where: { column: 'value' }
      });
    });
  };
});
```

#### Example to initialize on a specific marker by ID

```js
Fliplet.Hooks.on('flInteractiveGraphicsBeforeRender', function onBeforeRender(data) {
  return { markerId: 1234 };
});
```

#### Example to initialize on a specific marker by Name

```js
Fliplet.Hooks.on('flInteractiveGraphicsBeforeRender', function onBeforeRender(data) {
  return { markerName: 'marker one' };
});
```

#### Example to initialize on a specific map

```js
Fliplet.Hooks.on('flInteractiveGraphicsBeforeRender', function onBeforeRender(data) {
  return { mapName: 'marker one' };
});
```

### Run a hook when the marker label is clicked

```js
Fliplet.Hooks.on('flInteractiveGraphicsLabelClick', function onLabelClick(data) {
  return Fliplet.Navigate.screen(123);
});
```

---

[Back](../../API-Documentation.md)
{: .buttons}

### CODE REVIEW

**Comment by squallstar** [comment]
- flInteractiveMapBeforeGetData > OK
flInteractiveMapBeforeRenderMap > flInteractiveMapBeforeRender (no need for redundant map in name)
flInteractiveMapOnLabelClick > flInteractiveMapLabelClick (no need for redundant `On` since it's implicit from the hooks.on

**Comment by squallstar** [comment]
@hcarneiro I'm confused by things like `data.config.startOnMarker`, can't these be configured in the `
flInteractiveMapBeforeGetData` (since `data.config` is available there)?

If so, why adding so many hooks?

**Comment by squallstar** [comment]
@hcarneiro one more thing: in regards `data.config.labelAction to, keep in mind that will be overwritten if you have registered more than one hook to configure such variable, which means you're not making them hooks anymore.

This is my suggested approach:

```js
Fliplet.Hooks.on('flInteractiveMapLabelClick', function onLabelClick() {
  // the label was clicked
});
```

**Comment by squallstar** [comment]
One more suggestion for configuring the map start position:

```js
Fliplet.Hooks.on('flInteractiveMapConfigureInitialPosition', function () {
  return { name: 'Marker one' }
});
```

**Comment by hcarneiro** [comment]
@squallstar 
1- Only three hooks, and they have different life cycles
2- Agree
3- That suggestion doesn't allow me to do the 2 things that the `
flInteractiveMapBeforeRenderMap` allows the user to do

**Comment by squallstar** [comment]
@hcarneiro on `3` you just need to be more specific in what the hook returns:

```
return { markerId: '123 }
```

```
return { markerName: 'foo' }
```

```
return { mapName: 'foo' }
```

**Comment by hcarneiro** [comment]
@tonytlwu @squallstar Updated Docs in the top description.

PR with changes on the component incoming.

**Comment by tonytlwu** [comment]
My recommended updates modifies the documentaion to below.

---

# Interactive Graphics JS APIs

These public JS APIs are available in screens where an **Interactive Graphics** component is present.

## Hooks

The Interactive Graphics component exposes hooks that you can use to modify the component data and behavior. Here are the hooks and their specific life cycle:

- `flInteractiveGraphicsBeforeGetData` Fired before getting data source data
- `flInteractiveGraphicsBeforeRender` Before rendering the maps and markers
- `flInteractiveGraphicsLabelClick` After everything is rendered and the user clicks on the marker label

### `flInteractiveGraphicsBeforeGetData`

This hook is fired before getting data source data.

```js
Fliplet.Hooks.on('flInteractiveGraphicsBeforeGetData', fn);
```

#### Parameters

- **fn** (Function((Object) `data`)) Callback function with an object parameter
  - **data** (Object) Object containing properties listed below
    - **id** (Number) Component instance ID. This differs between master and production apps.
    - **uuid** (String) Component instance UUID. This is consistent between master and production apps.
    - **config** (Object) Component instance configuration.
    - **container** (DOM) Component instance container element.

### `flInteractiveGraphicsBeforeRender`

This hook is fired before rendering the maps and markers. You can use this hook to load the map with a specific marker selected. This will automatically select the correct map for the specified marker.

```js
Fliplet.Hooks.on('flInteractiveGraphicsBeforeRender', fn);
```

#### Usage

**Select a marker by ID**

```js
Fliplet.Hooks.on('flInteractiveGraphicsBeforeRender', function () {
  return { markerId: 1234 };
});
```

**Select a marker by name**

```js
Fliplet.Hooks.on('flInteractiveGraphicsBeforeRender', function () {
  return { markerName: 'Marker name' };
});
```

**Select a map by name**

```js
Fliplet.Hooks.on('flInteractiveGraphicsBeforeRender', function () {
  return { mapName: 'Map one' };
});
```

#### Parameters

- **fn** (Function((Object) `data`)) Callback function with an object parameter
  - **data** (Object) Object containing properties listed below
    - **id** (Number) Component instance ID. This differs between master and production apps.
    - **uuid** (String) Component instance UUID. This is consistent between master and production apps.
    - **config** (Object) Component instance configuration.
    - **container** (DOM) Component instance container element.
    - **markers** (Array) List of markers and associated data.

### `flInteractiveGraphicsLabelClick`

This hook is fired after everything is rendered and the user clicks on the marker label. Nothing is expected to be returned.

```js
Fliplet.Hooks.on('flInteractiveGraphicsLabelClick', fn);
```

#### Parameters

- **fn** (Function((Object) `data`)) Callback function with an object parameter
  - **data** (Object) Object containing properties listed below
    - **id** (Number) Component instance ID. This differs between master and production apps.
    - **uuid** (String) Component instance UUID. This is consistent between master and production apps.
    - **config** (Object) Component instance configuration.
    - **container** (DOM) Component instance container element.
    - **selectedMarker** (Object) Selected marker data.

## Configuration

Using the available hooks, component instance configuration can be used to modify component data and behavior. The available configuration properties are listed below:

- `cache` (Boolean) Set to `false` to always retrieve data from the server. **Default**: `true`.
- `getData` (Promise) Function used to return an array of entries. Each entry must include the following properties, which the `Fliplet.DataSources` JS API follows:
  - `id` (Number) Entry ID
  - `data` (Object) Entry data

## Examples

### Use custom data for the mapping

```js
Fliplet.Hooks.on('flInteractiveGraphicsBeforeGetData', function onBeforeGetData(data) {
  // disable caching the data so it's always retrieved from the server
  data.config.cache = false;

  // Define the "getData" promise to manually fetching data
  data.config.getData = function () {
    // In this example we connect to a data source with ID 123
    // Change the ID to your data source ID
    return Fliplet.DataSources.connect(123)
      .then(function(connection) {
      // Get all entries in the data source matching a specific condition
      return connection.find({
        where: { column: 'value' }
      });
    });
  };
});
```

### Initialize the component with a specific marker or map

```js
// Select marker with ID 1234
Fliplet.Hooks.on('flInteractiveGraphicsBeforeRender', function onBeforeRender(data) {
  return { markerId: 1234 };
});

// Select marker with name 'Marker one'
Fliplet.Hooks.on('flInteractiveGraphicsBeforeRender', function onBeforeRender(data) {
  return { markerName: 'Marker one' };
});

// Select map with name 'Map one'
Fliplet.Hooks.on('flInteractiveGraphicsBeforeRender', function onBeforeRender(data) {
  return { mapName: 'Map one' };
});
```

### Navigate to a screen when a marker is clicked

```js
Fliplet.Hooks.on('flInteractiveGraphicsLabelClick', function onLabelClick(data) {
  return Fliplet.Navigate.screen(123);
});
```

**Pull request merged**
