### PR TITLE
more docs on env vars

### PR DESCRIPTION
**Pull request by squallstar**

### CODE REVIEW

**Comment by squallstar** [comment]
@tonytlwu I intentionally didn't list it here because you shouldn't need to use it (same as `primaryApiUrl`).

I manually went through `Object.keys(window.ENV).sort()` FYI

**Comment by tonytlwu** [comment]
@squallstar Why isn't `appsUrl` needed? I've had to use it when coding features that use `Fliplet.Content()`, e.g. https://developers.fliplet.com/API/fliplet-content.html#share-a-page-with-a-url

**Comment by squallstar** [comment]
@tonytlwu it is not meant to be used by non-Fliplet devs because it can't be used in its raw state (http://apps.fliplet.com/ simply redirects to fliplet.com) unless you know why you're using it.

However, I wasn't aware of your example on the dev docs as I though you internally handled the mapping and only exposed the public generated url.

I'll amend the docs.

**Comment by tonytlwu** [comment]
@squallstar This should be very helpful. Hopefully, you'll be asked less of the question, "Is there a way to know [...]?" cc @hcarneiro

**Pull request merged**
