### PR TITLE
clone widgets

### PR DESCRIPTION
**Pull request by squallstar**
Once you have published a component on Fliplet, its source can now be retrieved at any time from any machine as long as you're logged in on the CLI with an account that has got access to it.

Simply use the `clone` command to download a copy of the source code, given a component package name:

```
$ fliplet clone com.fliplet.primary-button

Cloning widget Primary Button (com.fliplet.primary-button).

Please type the path where this widget should be saved to. Press return to use "widget-primary-button".
Done! Widget cloned to "widget-primary-button".
```

---

You can also list all components you have got access to, by using the `list` command as follows:

```
$ fliplet list

Here's the widgets you have access to and can be downloaded:

• Inline Link
  - Package name: com.fliplet.inline-link
  - Version: 1.0.0

• Primary Button
  - Package name: com.fliplet.primary-button
  - Version: 1.0.0

• Push notifications
  - Package name: com.fliplet.push-notifications
  - Version: 1.0.0

To download a widget, type: fliplet clone <packageName>
```

### CODE REVIEW

**Comment by ibroom** [comment]
Just to confirm I can clone > edit > commit?

Can I use this to get any of the public components e.g. primary button? This feature would be great because it means I can grab a public component, alter it but only commit it back to my organisation as a copy.

**Comment by squallstar** [comment]
@ibroom with the difference of `commit` being called `publish`, yes you can do that as long as you also change the package name to something which is unique and related to you. e.g. `com.fliplet-primary-button` to `com.foo.bar`.

**Comment by ibroom** [comment]
so I can clone, edit, publish any component in my account?

I can clone any public component but can't publish unless I change the name? Does the CLI give me a useful error message so I do this?

**Comment by squallstar** [comment]
@ibroom not the component name, **the package name** (as it needs to be unique). If you try to publish with a package name that is being used in the system:
- if you're a system admin, you can overwrite it with the source code you're pushing
- if you have got access to the widget (as an organisation admin), you can push the code
- if you have no write access to it, it's going to tell you that you have no access to such package

Having said that, I'm going to further improve the latter error message to point out that you might have to change its package name if you're uploading it brand new for your organisation.

**Comment by squallstar** [comment]
Update: PR improving the error messages is here https://github.com/Fliplet/fliplet-cli/pull/25

**Pull request merged**
